name: FOXY ros-model-extractors

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ros-model-extractors
    - name: Build the docker container for foxy
      run: |
        pushd ros-model-extractors
        docker build --tag=haros_foxy -f foxy/Dockerfile .
    - name: Analyse the ROS package test package for foxy
      run: |
        pushd ros-model-extractors
        docker run haros_foxy:latest /test.sh ros2Parameters

