name: NOETIC ros-model-extractors

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: ros-model-extractors
    - name: Build the docker container for noetic
      run: |
        pushd ros-model-extractors
        docker build --tag=haros_noetic -f noetic/Dockerfile .
    - name: Analyse the test ROS package for noetic
      run: |
        pushd ros-model-extractors
        docker run haros_noetic:latest /test.sh ros1Parameters
